name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Test with the Go CLI
        run: go test ./...
      - name: Build
        run: go build -v ./...
